# Generated by Django 3.2.9 on 2022-03-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsonly_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_price',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='amount',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
