# Generated by Django 3.2.9 on 2022-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsonly_admin', '0002_auto_20220313_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=-1, max_length=300),
            preserve_default=False,
        ),
    ]
